apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-api-31346
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-api-31346
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
